name: Create Release

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    name: Create deployable archive
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Setup PHP
        uses: shivammathur/setup-php@f3e473d116dcccaddc5834248c87452386958240 # 2.37.2
        with:
          php-version: "8.5"
          extensions: zip, json, gd, ftp
          tools: composer:2.10.2

      - name: Install dependencies
        run: composer install --no-dev --optimize-autoloader --no-interaction --prefer-dist

      - name: Ensure Ace assets
        run: bash ./scripts/ensure-ace-assets.sh

      - name: Create Archive
        run: |
          VERSION=$(grep 'public string $version' app/Config/App.php | sed -E "s/.*= '(.+)';/\1/")
          mkdir -p release/writable/cache/thumbs
          mkdir -p release/writable/logs
          mkdir -p release/writable/session
          mkdir -p release/writable/uploads
          mkdir -p release/writable/file_manager_root
          mkdir -p release/writable/shared
          mkdir -p release/writable/trash
          echo "[]" > release/writable/users.json
          cp -r app release/
          cp -r public release/
          cp -r vendor release/
          cp LICENSE.md README.md .htaccess nginx.conf.example release/
          cd release && zip -r ../eXtplorer-$VERSION-release.zip .

      - name: Release
        uses: softprops/action-gh-release@3d0d9888cb7fd7b750713d6e236d1fcb99157228 # v3.0.2
        with:
          files: eXtplorer-*-release.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
